GET http://localhost:4000/api/operations/
Authorization: JWT_TOKEN

###
GET http://localhost:4000/api/operations/?limit=5
Authorization: JWT_TOKEN

###
POST http://localhost:4000/api/operations/
Content-Type: application/json
Authorization: JWT_TOKEN

{
   "concept": "Devolvi dinero a Juan",
   "amount": 750,
   "type": "exit",
   "category": "Cajeros"
}

###
PATCH http://localhost:4000/api/operations/ff141684-612d-4e9c-aad6-729ca1342e3e
Content-Type: application/json
Authorization: JWT_TOKEN

{
   "category": "Restaurantes"
}

###
DELETE http://localhost:4000/api/operations/0e90a550-517b-4e85-81ca-37abeb9796b5
Content-Type: application/json
Authorization: JWT_TOKEN