version: '3.3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=carlos
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alkemy
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
      
volumes:
  postgres-data: